### ISSUE TITLE
Fruitful's oak tree configuredfeature is not registered

### ISSUE THREAD

**Issue by TelepathicGrunt** [teamauroramods/Fruitful-Forge#15]
Hello! Someone was running my mod called Blame with a small modpack and it seemed to have found that Fruitful's ConfiguredFeature form of its budding/flowering oak tree is not registered. This can be an issue for mod compatibility as under certain conditions, unregistered ConfiguredFeatures can basically prevent other mod's registered ConfiguredFeatures from spawning if in the same generation stage.

By that I mean, if mod A adds an unregistered CF to the ore generation stage and the biome's codec reaches it first, it will choke and basically nuke mob B's registered CFs afterwards. Here's a case where BetterCaves forgot to register their CF and caused several CFs from Oh The Biomes You'll Go to stop spawning in the world: yungnickyoung/YUNGs-Better-Caves#75

Here's a more detailed explanation of why this happens in the biome's codec:
![image](https://user-images.githubusercontent.com/40846040/95459000-ff41ee80-0940-11eb-8569-52a2be15cc4d.png)

Specifically, when you call .withConfiguration on a Feature, you create a ConfiguredFeature. This is what should be registered to the WorldgenRegisties at mod init (you can do it in FMLCommonSetupEvent so you have your config ready too if it is needed). 

Anyway here's an example from my mod RepurposedStructures of me registering all my ConfiguredFeatures.
https://github.com/TelepathicGrunt/RepurposedStructures/blob/584433a0745338802c84e9f498dc063c1f5505f8/src/main/java/com/telepathicgrunt/repurposedstructures/modinit/RSConfiguredStructures.java#L72-L74

I hope this helps!

From the log with Blame where it tried to figure out what unnamed configuredfeature is unregistered by parsing its json:

-----------------------------------------------------------------------
****************** Blame Report 1.9.0 ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered unnamed stuff belongs to.

Possible mods responsible for unregistered stuff:

fruitful:budding_oak_leaves
fruitful:flowering_oak_leaves

**Comment by ex0planetary** [comment]
Currently this is happening in fruitful.core.registry.FruitfulFeatures where I'm replacing the flower forest oak trees with flowering oak trees. It's in a ConfiguredRandomFeatureList so I dynamically adapt it so it just replaces the feature, not the chance in the CRFL. Not sure if there's any way of registering it in that scenario since it's not predefined.

Seeing as you're a lot more experienced than me with 1.16.2+ worldgen, do you know if there's any way I can get that registered? Code in question is [here](https://github.com/teamauroramods/Fruitful/blob/master/src/main/java/com/teamaurora/fruitful/core/registry/FruitfulFeatures.java) at lines 83-112.

**Comment by TelepathicGrunt** [comment]
Once BiomeLoadEvent fires, it is too late to register. Though you really dont need to add your tree to vanilla's MultipleRandomFeatureConfig. You can just make a configuredfeature that is nearly like Features.FOREST_FLOWER_TREES but uses your tree. 

Then in BiomeLoadEvent, you can iterate over the configuredfeatures in the flower forest biome for Features.FOREST_FLOWER_TREES by using this to know when it found it. (The configuredfeature instance is changed due to the codec processing on the biome so we have to compare the json)
https://github.com/TelepathicGrunt/RepurposedStructures/blob/584433a0745338802c84e9f498dc063c1f5505f8/src/main/java/com/telepathicgrunt/repurposedstructures/RSAddFeaturesAndStructures.java#L633-L645

Once found, you can just remove the configuredfeature from the biome directly and then add your configuredfeature. This way, everything remains registered and your configuredfeature replaced vanilla's
