### ISSUE TITLE
According to Blame, 2features of Fruitful aren't registered

### ISSUE THREAD

**Issue by BugmanBugman** [teamauroramods/Fruitful-Forge#25]
****************** Blame Report 1.16.5-3.0.1-forge ******************

 This is an experimental report. It is suppose to automatically read
 the JSON of all the unregistered ConfiguredFeatures, ConfiguredStructures,
 and ConfiguredCarvers. Then does its best to collect the terms that seem to
 state whose mod the unregistered stuff belongs to.

Possible mods responsible for unregistered stuff:

fruitful:budding_oak_leaves
fruitful:flowering_oak_leaves
]

**Comment by ex0planetary** [comment]
Huh, odd, thought I fixed that before release. I'll look into it on Monday.
