### ISSUE TITLE
1.16.2 Crash

### ISSUE THREAD

**Issue by mjlmjl888** [teamauroramods/Fruitful-Forge#3]
Here is the log this is after downloading the Fruitful-1.16.1-v1.2.2 update.

https://pastebin.com/CQK3x0ji

**Comment by ex0planetary** [comment]
Looks like your Abnormals Core is out of date. From what I've seen they deleted the old version and replaced it with the new version and it's not updating on peoples' ends, so you might have to try reinstalling it. Let me know if that works, if it doesn't I'll look into it further.

**Comment by mjlmjl888** [comment]
It still doesn't work https://pastebin.com/NPa6nsnQ

**Comment by ex0planetary** [comment]
Figured it out, apparently some changes in the deleted AC version were reverted so I had to change some stuff back. Fixed in dev, patch will be out soon.
